repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [--recursive,  -s, "B101"]
