language: python

install:
  - pip install poetry=='1.0.0b8'
  - poetry install

jobs:
  include:
    - stage: black
      script: poetry run black --check $(pwd)
      python: "3.6"
    - stage: black
      script: poetry run black --check $(pwd)
      python: "3.8"
    - stage: mypy
      script: poetry ru mypy $(pwd)/lunavl
      python: "3.6"
